aws/aws-elastic-beanstalk-cli

setup.py
#2
Updating botocore version to resolve awscli conflict.
The EB CLI botocore requirement is conflicting with the awscli botocore requirement. This PR increases the EB CLI botocore version range to conform to what is used by awscli.
---
=> Updating botocore version

ebcli/core/base.py
https://github.com/aws/aws-elastic-beanstalk-cli/issues/104
display full results when --version flag is specified
=> Update to display full results when --version flag is specified

ebcli/lib/codecommit.py, tests/unit/lib/test_codecommit.py
cr:https://code.amazon.com/reviews/CR-68895340
=> Update supported codecommit regions

ebcli/objects/region.py
*Description of changes:* add new region
=> Add new region (CGK)

ebcli/objects/region.py
SIM: https://i.amazon.com/V768093424
cr: https://code.amazon.com/reviews/CR-80479370
*Description of changes:* Added a new region KIX
=> Add new Region (KIX)

requirements.txt, tests/unit/core/test_abstractcontroller.py
=> Fix unit test bug

ebcli/bundled/asciimatics/exceptions.py, ebcli/bundled/asciimatics/screen.py, ebcli/bundled/asciimatics/utilities.py, ebcli/lib/s3.py, ebcli/objects/sourcecontrol.py, requirements.txt
https://nvd.nist.gov/vuln/detail/CVE-2022-40899
=> Update future package requirements to resolve CVE

CHANGES.rst, ebcli/__init__.py
cr: https://code.amazon.com/reviews/CR-86294270
=> Update CHANGES.rst and increment version to 3.20.4

ebcli/objects/region.py
Added TLV (Middle-East: Israel) region to EBCLI.
=> Add TLV region

ebcli/objects/region.py
Disabling TLV region till Launch Date
=> Deactivating TLV region till GA date

ebcli/objects/region.py
=> Minor update

.gitignore, requirements.txt
=> Version update

CHANGES.rst, ebcli/__init__.py
=> Update CHANGES.rst and increment version to 3.20.7

setup.py
Ideally either remove "local" support or migrate to latest docker compose
=> update requirement to last version of docker-compose v1

ebcli/operations/logsops.py, requirements.txt, tests/unit/operations/test_logsops.py
=> Al2023 fix

requirements.txt
Update based on PR#447
Updated six version .
=> Update six version

CHANGES.rst, ebcli/__init__.py
Updated Changes.rst and version 
=> Version upgrade

.github/dependabot.yml, CHANGES.rst, ebcli/__init__.py, ebcli/lib/cloudformation.py, ebcli/operations/logsops.py, requirements.txt, setup.py, tests/unit/operations/test_logsops.py
=> Merge from master

ebcli/containers/commands.py, ebcli/containers/utils.py, setup.py
*Issue #:456
Removing docker compose as a dependency
=> Removing docker-compose as a dependancy

ebcli/controllers/initialize.py, ebcli/operations/initializeops.py, tests/unit/controllers/test_init.py, tests/unit/operations/test_initializeops.py
=> Fix for bug showing distorted images

CHANGES.rst
=> merge from master 

CHANGES.rst
=> Update EBCLI CHANGES.rst for 3.21 release

README.rst, dev_requirements.txt, setup.py, tests/unit/objects/test_sourcecontrol.py
Upgrade pytest and pytest_socket.
=> Upgradepytest

CHANGES.rst, ebcli/__init__.py
Update version number and CHANGES.rst for 3.22 release
=> Update version number and CHANGES.rst for 3.22 release

CHANGES.rst
=> Update CHANGES.rst to indicate eb-health Windows fix

CHANGES.rst, ebcli/__init__.py
Update version number and CHANGES.rst for 3.23.2 release
=> Update version number and CHANGES.rst for 3.23.2 release

CHANGES.rst, ebcli/__init__.py
Update CHANGES.rst and version number to 3.24
=> Update CHANGES.rst and version number to 3.24

ebcli/__init__.py
=> Update version to 3.24.1
