aws/aws-elastic-beanstalk-cli

setup.py
Updating docker-compose so that the ebcli can update it's version of pyyaml.
Pyyaml in version 4.x has a few security vulnerabilities, currently no versions of 4 are supported on the ebcli so we are skipping 4 and going straight to 5.x. This comes with the update of docker-compose that has recently added support for a similar range in pyyaml.
=> Update pyyaml and docker-compose versions

setup.py
The awscli has the highest limit for PyYaml set to 5.3, so the ebcli needs to follow this limit rather than 5.4.
=> Lower limit of PyYAML for awscli

ebcli/core/fileoperations.py, tests/unit/operations/test_commonops.py, tests/unit/operations/test_ebignore.py
I've made a small change to the .ebignore implementation to use a set instead of a list.
The ignore list is only used when creating an application version and zipping up the project. For each and every file in the project, the current implementation iterates over the ignore list looking for a match.
Using a set instead cuts the time required to create application versions in my project from ~46 seconds down to ~6 seconds.
=> Use a set for the .ebignore list

setup.py
Could you fix this problem?
```bash
$ poetry add awsebcli
Using version ^3.17.1 for awsebcli
Updating dependencies
Resolving dependencies... (0.3s)
[SolverProblemError]
Because no versions of docker-compose match >1.25.2,<1.25.3 || >1.25.3,<1.25.4 || >1.25.4,<1.26.0
and docker-compose (1.25.2) depends on colorama (>=0.4,<1), docker-compose (>=1.25.2,<1.25.3 || >1.25.3,<1.25.4 || >1.25.4,<1.26.0) requires colorama (>=0.4,<1).
And because docker-compose (1.25.3) depends on colorama (>=0.4,<1)
and docker-compose (1.25.4) depends on colorama (>=0.4,<1), docker-compose (>=1.25.2,<1.26.0) requires colorama (>=0.4,<1).
And because awsebcli (3.17.1) depends on both colorama (>=0.3.9,<0.4.0) and docker-compose (>=1.25.2,<1.26.0), awsebcli is forbidden.
So, because no versions of awsebcli match …
```
=> Fix colorama version conflict

ebcli/core/fileoperations.py, requirements.txt, tests/unit/core/test_fileoperations.py, tests/unit/operations/test_ebignore.py
*Overview:* 
.ebignore includes symlinked files in ignored directories
Fixed [Issue#69](https://github.com/aws/aws-elastic-beanstalk-cli/issues/69)
Fixed bug where a folder mentioned in **.ebignore** file was being included in the final code.zip on running `eb deploy`. This was due to the presence of a **symlink** within that folder.
Changes
1. Added method to check if current file being checked for ignore/include exists in the ignore_list.
2. Updated the **Pathspec** library to latest version i.e. **0.10.1**
3. Changed method in get_ebignore_list() function from match_tree to math_tree_entries.
> .ebignore contents = ignore/ , Before: we were getting ignore/.... but not just ignore/ After: we get ignore/... and just ignore/ too.
4. Updated Unit test case.
By …
=> Fixed a Unit Test Bug

ebcli/controllers/ssh.py, ebcli/operations/sshops.py, ebcli/resources/strings.py, tests/unit/controllers/test_ssh.py, tests/unit/operations/test_sshops.py
This PR Fixes [Issue 3](https://github.com/aws/aws-elastic-beanstalk-cli/issues/3) 
Add --prefer-private-ip argument to the eb ssh command #89
In this PR I have updated the failing unit tests of an older PR titled _"Add --prefer-private-ip argument to the eb ssh command #89"_ by user github user @blampe.
=> Updated failing Unit Tests to old PR: Add --prefer-private-ip argument to the eb ssh command #89

ebcli/lib/iam.py, ebcli/operations/buildspecops.py, tests/unit/operations/test_buildspecops.py, tests/unit/operations/test_commonops.py
*Issue:*
When codebuild is used, a buildspec.yml file is present in the application package. It has configuration settings for incorporating codebuild in your application. The CodeBuildServiceRole given in that file can be either an arn (arn:aws:iam::123456789123:role/aaa1234) or (arn:aws:iam::123456789123:role/service-role/zzxxyy) or just role-name (codebuild-service-role-zzxxyy). In ebcli codebase we call the iam.list_roles api to get all the iam roles. There is a limit on the count retrieved by default(100). Earlier, if there were more than 100 roles in IAM it was throwing an exception if the role wasn't fetched in the first 100 itself.
Solved this by checking for more roles after the first api call and searching for the desired role until all roles present in …
=> Codebuild bugfix

ebcli/objects/solutionstack.py
EBCLI was picking up older Corretto version (Corretto 8) for java when running command: `eb create --single -p "corretto"`. Instead it should choose Corretto 17 which is the latest.
=> Platform Bugfix

requirements.txt
Should fix #441
This PR updates PyYAML limit in order to match with awscli.
https://github.com/aws/aws-cli/pull/8037
=> Increase PyYAML limit as awscli

requirements.txt
*Issue #, if available:385
*Description of changes:This fixes an incompatibility regarding DEFAULT_CIPHERS being removed in urllib3 v2 by pinning urllib3 on >=1.26.5, <2. Resolved merge conflicts and updated code as per pull request .
=> Update urllib3 in  requirements.txt

ebcli/operations/sshops.py, tests/unit/operations/test_sshops.py
=> Fix for issue #144

ebcli/controllers/create.py, tests/unit/controllers/test_create.py
=> Fix for lb setting when using .ebextensions or save config files

ebcli/__init__.py
Upgrade version to 3.21 in code so that it gets packaged as such. Verified that it creates a 3.21 artifact:
```
Writing awsebcli-3.21.0/setup.cfg
```
=> Upgrade EBCLI version to 3.21.0

setup.py
installing awebcli using https://github.com/pypa/installer fails due to eb being listed in both `scripts` and `entry_points`
```
error: builder for '/nix/store/swk28rqdv15g8v383al28kzjvigdp4y8-awsebcli-3.20.7.drv' failed with exit code 1;
last 10 log lines:
>     _main(sys.argv[1:], "python -m installer")
>   File "/nix/store/qg1mq5b71pbhnvpa8l1024prdymn2hkc-python3.10-installer-0.7.0/lib/python3.10/site-packages/installer/__main__.py", line 94, in _main
>     installer.install(source, destination, {})
>   File "/nix/store/qg1mq5b71pbhnvpa8l1024prdymn2hkc-python3.10-installer-0.7.0/lib/python3.10/site-packages/installer/_core.py", line 109, in install
>     record = destination.write_file(
>   File "/nix/store/qg1mq5b71pbhnvpa8l1024prdymn2hkc-python3.10-installer-0.7.0/lib/python3.10/site- …
```
=> remove duplication with entry_points

ebcli/display/traditional.py, ebcli/lib/utils.py, ebcli/objects/solutionstack.py, ebcli/operations/buildspecops.py, ebcli/operations/commonops.py, ebcli/operations/logsops.py, setup.py, tests/test_dependencies_mismatch.py, tests/unit/containers/test_log.py, tests/unit/integration/test_health.py, tests/unit/integration/test_profile_selection.py, tests/unit/lib/test_utils.py, tests/unit/objects/test_platform.py, tests/unit/operations/test_commonops.py
Address the following deprecation warnings
- Use `datetime.now(UTC)` in favour of `datetime.utcnow()`
- Removed usage of the deprecated `pkg_resources` module in favor of the `packaging` and `importlib` packages:
-------
```
============================================================================================== warnings summary ===============================================================================================
tests/unit/integration/test_health.py::TestHealth::test_health__refresh
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/unittest/case.py:589: RuntimeWarning: coroutine 'TestHealth.test_health__refresh' was never awaited
if method() is not None:
Enable tracemalloc to get traceback where the object was allocated.
See …
```
=> Address deprecated uses

ebcli/controllers/initialize.py, ebcli/resources/strings.py, tests/unit/controllers/test_init.py
This commit provides a way to specify the environment name to use as the default environment for the workspace. This allows for a way to avoid executing the `eb use` command after initialization.
=> Provide a way to specify the environment name to use with 'eb init'

ebcli/display/traditional.py, ebcli/lib/utils.py, ebcli/operations/buildspecops.py, ebcli/operations/commonops.py, ebcli/operations/logsops.py, tests/unit/containers/test_log.py, tests/unit/lib/test_utils.py, tests/unit/operations/test_commonops.py
This change fixes breakages introduced to the master branch by a previous PR merge that removed usages of `datetime.UTC` which was introduced only in Python 3.11.
=> Fix 3.8, 3.9 backwards incompatibility caused by use of datetime.UTC

ebcli/controllers/deploy.py, ebcli/lib/s3.py, ebcli/operations/commonops.py, ebcli/operations/deployops.py, ebcli/resources/strings.py, tests/unit/controllers/test_deploy.py, tests/unit/integration/test_deploy.py, tests/unit/lib/test_s3.py, tests/unit/lib/test_s3_upload_workspace.py, tests/unit/operations/test_commonops.py, tests/unit/operations/test_deployops.py, tests/unit/operations/test_deployops_source_bundle.py
[This PR replaces #535]
This commit adds support `eb deploy ... --archive <ZIP|dir>` so that customers can point to arbitrary directories/ZIP files to deploy to existing environments. In the presence of the `--archive` argument, `eb deploy` will ignore the `.elasticbeanstalk/config.yml` file if it is present. If it is not present, it will operate in its absence. The `--archive` argument will accept directories or ZIP files. If the argument is a directory, `eb deploy` will ZIP the directory and save it in the `~/.ebartifacts/archives` directory. It will upload it to S3 and invoke `EB::CreateApplicationVersion` with the artifact. Like with the `eb-deploy` flow without `--archive`, it will proceed to perform an `EB::UpdateEnvironment` and wait for the update to …
=> Peripheral eb migrate enhancements

ebcli/display/term.py
Fix issue with eb health --refresh on Windows where the health screen does not load properly and it refreshes frequently. By default, Python's print() function adds a newline character (\n) at the end of the output. The end='' parameter overrides this behavior, telling Python not to add a newline. In Windows this causes a carriage return which resets the cursor location from the location that we saved. As a result, the EB CLI is not able to resume updating and this results in flickering as it reset the cursor position.
*Testing:*
Tested command on Windows instance, observed properly terminal formatting with refresh occurring at expected interval and no flickering. Test on Mac OS as well and existing behavior is preserved.
By submitting this pull request, I …
=> Fix issue with eb health --refresh on Windows

CHANGES.rst, ebcli/__init__.py, requirements.txt
See https://github.com/aws/aws-elastic-beanstalk-cli/issues/541.
We deprecated usage of pkg_resources in favour of packaging but did not add explicit dependency on packaging.
=> Set explicit dependency on packaging

CHANGES.rst, ebcli/__init__.py, ebcli/controllers/migrate.py
Prevent execution of 'eb migrate' on non-Windows and fix info messages
=> Prevent execution of 'eb migrate' on non-Windows and fix info messages

ebcli/controllers/migrate.py
Fix typing syntax legal only on Python 3.10 and beyond.
Technically, we do not support Python 3.8 since it is EOL as of September 2024, but we haven't dropped support either. SO the correct thing to do is fix this.
=> Fix unrecognized type definitions for Python 3.8

ebcli/core/fileoperations.py, tests/unit/core/test_fileoperations.py
Fixes #511
Resolves #69 
This restores partially commit 790cde6b7b08d0d69ce44064cdf395f1cc5e5817, which effectively prevents including symlinks to directories as pointed out in #511. 
The function `is_parent_directory_in_ignore_list` was removed because it was doing a very inefficient M*N lookup (M: number of dirs and files, N: number of entries in ignore_list which include all subdirectories and files). This part was not restored. 
*Manual testing:*
Done with Python 3.9.18 and Python 3.12.10
Set up the following local directories
```
├── dummy.zip
├── file_a
├── folder_a
│   └── folder_b
│       └── file_b
├── ignore
│   ├── dir
│   │   └── ignored_file
│   └── symlink -> /home/yuxiang/tmp/511/folder_a
└── symlink_to_folder_b -> …
```
=> Zip symlinks-to-directories

CHANGES.rst, ebcli/__init__.py, ebcli/controllers/migrate.py, ebcli/resources/strings.py
=> Update string messages, CHANGES.rst and version number to 3.23.3

ebcli/controllers/migrate.py, ebcli/controllers/migrate_scripts/reinstate_iisstart_htm_default_document.ps1, requirements.txt
This change is to extend the existing eb migrate command's capabilities to allow for remote execution. It is now possible to install the eb cli on a bastion host and connect to the production machine, extract its IIS setup, and launch an environment all without installing anything on the production machine. This provides a safer, more managed and less invasive way for customers to migrate their IIS resources to Beanstalk.
=> Add EB Migrate Remote Execution Capability

ebcli/controllers/migrate.py, tests/unit/controllers/test_migrate.py
Follow up on PR #567 
- Updating error message to reflect IIS installation check.
- Updating migrate tests for the new error messages.
=> Updating error message for IIS installation check in migrate
